spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wallet
    username: user
    password: password

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true